### ISSUE TITLE
Unable to run Involution on ImageNet dataset

### ISSUE THREAD

**Issue by guoqingbao** [ChristophReich1996/Involution#1]
RuntimeError: CUDA out of memory. Tried to allocate 37.52 GiB (GPU 0; 10.76 GiB total capacity; 1.61 GiB already allocated; 7.97 GiB free; 1.63 GiB reserved in total by PyTorch)

The extreme high memory requirement (37.52 GiB) is not reasonable!

**Comment by ChristophReich1996** [comment]
Hi, can you provide some more information, especially your input resolution? Generally, this implementation of the Involution isn't as memory efficient as the [CuPy implementation](https://github.com/d-li14/involution) provided by the authors ([see readme](https://github.com/ChristophReich1996/Involution/blob/master/README.md)). This is due to the fact that the native PyTorch implementation utilizes the [unfold operation](https://pytorch.org/docs/stable/generated/torch.nn.Unfold.html) which is [memory extensive for high-resolutions](https://github.com/pytorch/pytorch/issues/31655).

Cheers 
Christoph

**Comment by guoqingbao** [comment]
Input resolution is 3x244x244.

**Comment by ChristophReich1996** [comment]
OK, at which batch size? Which parameters are utilized for the Involution?

**Comment by guoqingbao** [comment]
256, 128, and no luck even for 64
________________________________

**Comment by ChristophReich1996** [comment]
So, I guess, using the efficient CuPy implementation of the authors is the best way to go before sacrificing a sophisticated batch size. Another (time-consuming) solution would be to write a custom CUDA extension for the Involution, as suggested by the authors ([see their readme](https://github.com/d-li14/involution/blob/main/README.md)). Furthermore, using a larger GPU would probably be the fasters but least economic solution ;)
