### ISSUE TITLE
Problem with tensor size

### ISSUE THREAD

**Issue by nagadit** [ChristophReich1996/Involution#12]
![image](https://user-images.githubusercontent.com/24617421/124163004-ce45b300-daa7-11eb-861a-7d3097491216.png)
I replaced the Conv2D with a Involution2D and it stopped working for me, the parameters are the same, what can I do?

**Comment by ChristophReich1996** [comment]
Hi @nagadit, you encountered the edge case in which a shape mismatch occurs. The shape produced by the unfold operation (with 4 x 4 kernel) can not be reached by the reduce and span mapping since both the reduce and the span mapping consists of a 1 X 1 convolution. This can also occur for non-square kernels as discussed in #8. A possible solution would be to use a different kernel size with padding (same padding).

Cheers Christoph
