### ISSUE TITLE
conv_transpose2d

### ISSUE THREAD

**Issue by BehzadBozorgtabar** [ChristophReich1996/Involution#6]
Hi,

What should be the correct format of using 2D involution for the transposed convolution (F.conv_transpose2d)?

**Comment by ChristophReich1996** [comment]
Hey, you could try this approach.

```python
import torch
from involution import Involution2d
involution = Involution2d(in_channels=6, out_channels=12)
input_ = torch.rand(1, 6, 4, 4)
input = torch.zeros(1, 6, 8, 8)
input[..., ::2, ::2] = input_
output = involution(input)
```

I guess this should work since, the transposed convolution can be interpreted as a normal convolution with a checkerboard-like input, [see](https://datascience.stackexchange.com/questions/6107/what-are-deconvolutional-layers). But be aware, there could be a more efficient way to write this! This was only the first solution I had in mind.

Cheers 
Christoph
